### ISSUE TITLE
eventgen error

### ISSUE THREAD

**Issue by abeeber** [ericksond/splunk-essentials#3]
Hi Erick,

I'm getting an eventgen error:
2017-03-30 10:14:37,769 ERROR Exception in sample: destinations.sample
Traceback (most recent call last):
  File "/Applications/Splunk/etc/apps/SA-Eventgen/bin/eventgen.py", line 47, in run
    partialInterval = self.sample.gen()
  File "/Applications/Splunk/etc/apps/SA-Eventgen/lib/eventgensamples.py", line 582, in gen
    if self.sampletype == 'csv' and (eventsDict[x]['index'] != self.index or \
IndexError: list index out of range

I'm not getting many events from eventgen.

I noticed that PackT has some code files associated with the book. But them seem older. Should I use them?

**Comment by ericksond** [comment]
Not sure if eventgen updated something, but you can try to change the count value in the eventgen.conf file then restart Splunk

**Comment by ericksond** [comment]
Or create a second entry in the destinations.sample file, maybe clone the first row and tweak the next.

**Comment by abeeber** [comment]
Hi Erickson, 
Thanks for the response.
So here is what I did.

I increased the count to 25.

I moved token 7 (status codes) above token 5 in my eventgen.conf; and relabelled them chronologically.

I revised the list files by changing their file name from .sample to .list and also updated their listing in the eventgen.conf.

I also changed the integer ranges - the first 100-1000, the second 1001-4000.

I'm still getting the error, but at least I am seeing more events. 

The joys of eventgen!

**Comment by abeeber** [comment]
Hi Erickson,

I fixed it. I'm not sure if using Splunk 6.5.2/3 caused a problem or not. I also checked EventGen had not been updated in months.

Here is your eventgen.conf with my changes:

[destinations.sample]
host = www.destinations.com
source = web_log
sourcetype = access_custom
mode = sample
sampletype = raw
outputMode = splunkstream
splunkUser = admin
splunkPass = xxxxxxx

interval = 10
earliest = -10s
latest = now
index = main
count = 25
randomizeCount = 0.33
randomizeEvents = true

token.0.token = ((\w+\s+\d+\s+\d{2}:\d{2}:\d{2}:\d{3})|(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}:\d{3}))
token.0.replacementType = replaytimestamp
token.0.replacement = ["%b %d %H:%M:%S:%f", "%Y-%m-%d %H:%M:%S:%f"]

token.1.token = (CLIENT_IP)
token.1.replacementType = file
token.1.replacement = $SPLUNK_HOME/etc/apps/destinations/samples/external_ips.list

token.2.token = (SERVER_IP)
token.2.replacementType = file
token.2.replacement = $SPLUNK_HOME/etc/apps/destinations/samples/webhosts.list

token.3.token = (Method-And-URI)
token.3.replacementType = file
token.3.replacement = $SPLUNK_HOME/etc/apps/destinations/samples/destinations-uris.list

token.4.token = (User-Agent)
token.4.replacementType = file
token.4.replacement = $SPLUNK_HOME/etc/apps/destinations/samples/useragents_desktop.list

token.5.token = (100)
token.5.replacementType = file
token.5.replacement = $SPLUNK_HOME/etc/apps/destinations/samples/http-codes.list 

token.6.token = (x)
token.6.replacementType = random
token.6.replacement = integer[100:1000]

token.7.token = (y)
token.7.replacementType = random
token.7.replacement = integer[1001:4000]


Here is your destinations.sample:

2016-09-14 17:29:11:000,CLIENT_IP,Method-And-URI,-,80,-,SERVER_IP,User-Agent,100,0,0,x,y

Note, I changed the token names and updated the sample file accordingly. 

As a result, I do not have the error initially reported and now have 600+ events over the last 5 minutes.
